Enabled autoescape for render context and using unescape for plain email parts.
vintasoftware/django-templated-email pull request #111
Opened 2018-07-05 12:33 UTC by ComradeDOS

This commits closes #108 and #109

2018-10-25 13:07 UTC, ComradeDOS commented
Python3.3 not available for travis anymore.

2021-05-28 13:33 UTC, fjsj commented on tox.ini
> +    {py27,py34,py35,py36}-django18,
Drop those changes, keep only main `tox.ini`

2021-05-28 13:35 UTC, fjsj requested changes
thanks for the PR @ComradeDOS , @tuliolages is a maintainer that will make some fixes and merge this

2021-05-28 13:39 UTC, fjsj commented
For now I'll close this one in preference of https://github.com/vintasoftware/django-templated-email/pull/120 which uses a simpler solution. Thanks for the PR and sorry we couldn't review it before.

2021-05-28 13:39 UTC, closed without merging